name: LÃ¸kki
favicon: null
layout_spectrum: 0.34890423994511366
typography_spectrum: 0.925938778789714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d1d8de'
    - '#94a6a4'
    - '#687b72'
    - '#dbb03f'
  brandStrength: 0.5
  lightness: 0.03713691863231361
  saturation: 0.5470558130182326
  rhythmicContrast: 0.7878540672827512
purpose: []
