name: LÃ¸kki
favicon: null
layout_spectrum: 0.34890423994511366
typography_spectrum: 0.925938778789714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5180774661712348
  lightness: 0.03713691863231361
  saturation: 0.5470558130182326
  rhythmicContrast: 0.7878540672827512
purpose: []
